services:
  polythought:
    build: .
    restart: always
    container_name: polythought
    volumes:
      - ./db:/app/db
      - ./credentials:/app/credentials
      - ./.cache:/app/.cache
    networks:
      - polythought
    env_file:
      - path: env/prod.env
        required: true
    environment:
      TZ: Asia/Singapore

networks:
  polythought:
